export const INCREMENT_WEIGHT = 'INCREMENT_WEIGHT';
export type INCREMENT_WEIGHT = typeof INCREMENT_WEIGHT;

export const DECREMENT_WEIGHT = 'DECREMENT_WEIGHT';
export type DECREMENT_WEIGHT = typeof DECREMENT_WEIGHT;

export const SET_WEIGHT = 'SET_WEIGHT';
export type SET_WEIGHT = typeof SET_WEIGHT;
